# Site
name: "영욱 | Youngwook"
title: "Friend | 친구 | 79"
description: "Knowing is not enough. I must apply. </br> Willing is not enough. I must do."
yklogo: 'assets/images/yklogo.png'
favicon: 'assets/images/yklogo.png'
baseurl: 
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'YK'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: kimkevin512@naver.com

# Authors
authors:
  sal:
    name: Youngwook
    display_name: YK
    avatar: 'assets/images/avatar-sal.png'
    email: kimkevin512@naver.com
    web: 
    twitter: 
    description: "40대란 나이가 새삼스럽게 다가옵니다. 늦은건 아닌지 걱정하기 보다 하루에 하나씩 채워나가기 위해 블로그를 시작합니다."
  # john:
  #   name: John
  #   display_name: John    
  #   avatar: 'assets/images/avatar.png'
  #   email: kimkevin512@naver.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

theme: jekyll-theme-cayman